

#require(superheat)
#require(rword2vec) #and others


###### Purpose

We want to test Google's famous `word2vec` result $\mathrm{king} - \mathrm{man} + \mathrm{woman} = \mathrm{queen}$. This particular result fits our semantic intuition, but how many other equations come as close?



###### Tolerance

Chris wants to make

```{r}
close <- .1
message(close, "should be as close as king - man + woman.")
close -> good.enough

close.but.not.close.enough <- .5
messages("how to index ", close.but.not.close.enough, "? maybe a slider in a sh.")


too.far <- 5
message(too.far, " should be so far out that ridiculous non-results would be inclued if you (fairly) included the spheres of distance ", too.far)
```


## Data sources

- subtitle files
- examples others provide
- Rob: **SAT analogy books!**
- Chris: any equations with more subtraction terms?
- Chris: bring a dictionary



## tests

- Brian: `king - dress + = queen`
- Brian: `king + free movement + ace|killer - monarch = queen`
-



## graphs


##### desiderata

try to test "shades" of meaning. Rob's example: «it’s pouring» versus «it’s raining» --- pouring is indeed more idiomatic and familiar (Rob’s example: tell someone you’ll be late for a business meeting because it’s pouring? no..)





# Analogies

Rob pointed out that analogies like `calf : cow :: piglet : pig`, etc. But what is really the structure of some of these?

Take `tree : forest :: tire : car`. This analogy might not be accepted as clearly right. Trees are part of a forest—as tires are part of a car. But tires are seen to be a heterogeneous part of a car, whereas a big enough collection of trees is seen to equal a forest. Then again --- trees _are_ a heterogeneous part of a forest, as forests have a canopy — underbrush — frogs — berries — dead pine needles — moss — and so on.
